### ISSUE TITLE
STEP2処理中にSTEP1のURLに戻ると、再度読み込み時にUIがクラッシュする

### ISSUE THREAD

**Issue by Syuparn** [codeforjapan/OpenDataTools#131]
現象

- STEP2でデータ自動変換中に、ブラウザの戻るボタン or URL `/upload-file` 入力でSTEP1の画面に強制的に戻ると、再度STEP1でcsvファイルを読み込んだ際にSTEP2完了時にUIがクラッシュすることがある
- 一度クラッシュすると、以降はブラウザをリロードしてもSTEP2完了のたびにクラッシュするようになる

再現方法

1. STEP1でcsvファイルを選択
1. STEP2でのデータの自動変換中に、STEP1のURL  `/upload-file` へ遷移する
1. 再度STEP1でcsvファイルを選択
1. STEP2でデータの自動変換が完了するのを待つ
1. 自動変換完了とともにUIが白い画面になり、何も表示されなくなる
1. (5.で正常に完了した場合は、1~2を数回連続で繰り返すと再現する確率が上がる)

備考

- console上から `localStorage.clear()` を実行すると解消する
  - localStorageのデータが中途半端な状態で残っているのが原因？

**Comment by Syuparn** [comment]
発生したエラー
（Chrome環境開発タブより）

```
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'datasetSingleCell__{"datasetUid":"67b37fd7-7f16-40a2-ab1e-404c70b24a3d","singleCellUid":"c807d255-fca1-4e11-bec0-36b235042499"}' exceeded the quota.
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:30679
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1616544
    at Pn (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1583325)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584290
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584534
    at Object.enqueueExecution (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1550549)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584103
    at nl (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1463804)
    at wu (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1484031)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1480621
fs @ react-dom.production.min.js:189
r.callback @ react-dom.production.min.js:189
Ni @ react-dom.production.min.js:144
bl @ react-dom.production.min.js:262
_l @ react-dom.production.min.js:260
gl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
xu @ react-dom.production.min.js:281
lu @ react-dom.production.min.js:273
Vo @ react-dom.production.min.js:127
wu @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
w @ scheduler.production.min.js:13
I @ scheduler.production.min.js:14
```

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'datasetSingleCell__{"datasetUid":"67b37fd7-7f16-40a2-ab1e-404c70b24a3d","singleCellUid":"c807d255-fca1-4e11-bec0-36b235042499"}' exceeded the quota.
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:30679
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1616544
    at Pn (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1583325)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584290
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584534
    at Object.enqueueExecution (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1550549)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1584103
    at nl (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1463804)
    at wu (https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1484031)
    at https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js:2:1480621
Vo @ react-dom.production.min.js:127
wu @ react-dom.production.min.js:286
(anonymous) @ react-dom.production.min.js:282
w @ scheduler.production.min.js:13
I @ scheduler.production.min.js:14
```

**Comment by Syuparn** [comment]
firefoxでも再現

```
DOMException: The quota has been exceeded. [react-dom.production.min.js:189:29](https://open-data-tools.vercel.app/static/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 14
        fs
        callback
        Ni
        bl
        _l
        gl
        xu
        xu
        lu
        Vo
        nu
        (非同期: VoidFunction)
    nu
        ru
        rs
    call index.js:5
    call index.js:5
    A index.js:5
    l index.js:5
```

```
Uncaught DOMException: The quota has been exceeded. [main.f9ecd6c4.js:2](https://open-data-tools.vercel.app/static/js/main.f9ecd6c4.js)
    effects dataset.ts:234
    a index.js:8090
    Pn index.js:4167
    In index.js:4216
    In index.js:4266
    enqueueExecution index.js:756
    In index.js:4265
    React 3
        nl
        wu
        lu
    lu self-hosted:1406
    React 5
        Vo
        nu
        (非同期: VoidFunction)
    nu
        ru
        rs
    rs self-hosted:1518
    call index.js:5
    forEach self-hosted:203
    call index.js:5
    A index.js:5
    l index.js:5
```
