### ISSUE TITLE
緯度、経度が空欄or整数値の場合にSTEP4の画面がクラッシュしてしまう

### ISSUE THREAD

**Issue by Syuparn** [codeforjapan/OpenDataTools#199]
発生したエラー

```
Uncaught RangeError: Invalid array length
    at orgRoundAtSix (MapEditorModal.tsx:41:1)
    at convertLngLat (MapEditorModal.tsx:45:1)
    at MapEditorModal.tsx:49:1
    at updateMemo (react-dom.development.js:17246:1)
    at Object.useMemo (react-dom.development.js:17886:1)
    at useMemo (react.development.js:1650:1)
    at MapEditorModal (MapEditorModal.tsx:49:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
```

**Comment by Syuparn** [comment]
修正箇所も見つかったのでこちら着手したいと思います！

**Comment by kaizumaki** [comment]
#201 をマージしたのでこちらのissueはクローズしますね。
